name: auto update proxy pool

on:
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'test'
                required: true
                default: 'warning'
            tags:
                description: 'test'
    schedule:
        - cron: '30 * * * *'

permissions: write-all

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up Python 3.9
              uses: actions/setup-python@v4
              with:
                  python-version: 3.9
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: 'Working'
              run: 
                  python3 ./run.py
            - name: commit
              run: |
                  git config --global user.email ${{ secrets.USER_EMAIL }}
                  git config --global user.name ${{ secrets.USER_NAME }}
                  git add .
                  git commit -m "github actions 自动更新" -a
            - name: Push changes
              uses: ad-m/github-push-action@master
              env:
                  REPO: self
                  BRANCH: test
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
